apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debezium-finance-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: managed-csi
  volumeMode: Filesystem
