apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.name" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
