# This is a basic workflow that is manually triggered

name: Deploy to dev-aks

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-dev:
    strategy:
      matrix: 
        resource: [dev]
        cluster: [dev-eastus-aks]
    runs-on: ubuntu-latest
    steps:
    - name: create temporary directories
      run: |
        mkdir deploy-configs
    - name: 'Auth with Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Auth with AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GITHUBACTIONSRO_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.GITHUBACTIONSRO_SECRET_KEY }}
        aws-region: us-east-1
    - name: Set AKS Context
      run:
        az aks get-credentials --name ${{ matrix.cluster }} --resource-group ${{ matrix.resource }}
    - name: applies kubectl configs and secrets
      run: |
        aws secretsmanager get-secret-value --region us-east-1 --secret-id platform/dev-aks/secret/koddi-debezium-finance --query SecretString --output text > deploy-configs/koddi-debezium-finance-secrets.yaml     
        kubectl apply -f deploy-configs/koddi-debezium-finance-secrets.yaml --dry-run=server
        kubectl apply -f deploy-configs/koddi-debezium-finance-secrets.yaml 

    - name: "Deploy Helm Chart"
      run: |
        helm plugin install https://github.com/hypnoglow/helm-s3.git
        helm repo add ${{ github.event.repository.name }} s3://helm-koddi/stable/koddi-debezium-finance/
        helm repo list
        helm search repo ${{ github.event.repository.name }}/koddi-debezium-finance --versions
        helm upgrade --install --devel ${{ github.event.repository.name }} ${{ github.event.repository.name }}/${{ github.event.repository.name }} --version 1.0.0-dev-eastus-aks --set podAnnotations.time=t${{needs.build-image-and-push-to-acr.outputs.date}}  --set image.tag=${GITHUB_REF##*/}-${{needs.build-image-and-push-to-acr.outputs.sha}}
  
